## 1 NumPy Array Explorer

In [141]:
# Demonstrate NumPy array creation methods and basic operations

import numpy as np

arr = np.array([2,4,6,8,10,12,14,16,18,20])
print(arr)

np.zeros([3,3])
# np.random.rand(2,45,33,67,95)

number = np.linspace(0,5,10)
print(number)

[ 2  4  6  8 10 12 14 16 18 20]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

In [142]:
arr.shape

(10,)

In [143]:
arr.dtype

dtype('int64')

In [144]:
arr.size

10

In [145]:
arr.ndim

1

In [146]:
arr.reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [147]:
x = arr.max()
y = arr.min()
print(x)
print(y)
arr[9]
arr[0]

20
2

np.int64(2)

In [148]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

arr2[0,1]

np.int64(2)

## 2 NumPy Array Math Wizard

In [149]:
# Demonstrate broadcasting and universal functions.

import numpy as np

arr1 =np.array([[1,2,3],[4,5,6]])
arr2 =np.array([10,20,30])

arr3 = arr1 + arr2
print(arr3)
arr4 = arr1 - arr2
print(arr4)
arr5 = arr1 * arr2
print(arr5)
arr6 = arr1 % arr2
print(arr6)

[[11 22 33]
 [14 25 36]]
[[ -9 -18 -27]
 [ -6 -15 -24]]
[[ 10  40  90]
 [ 40 100 180]]
[[1 2 3]
 [4 5 6]]

In [150]:
arr10 = np.array([1,4,9,16,25])
print(np.sqrt(arr10))
print(np.exp(arr10))
print(np.sin(arr10))

[1. 2. 3. 4. 5.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]

In [151]:
arr11 = np.array([[5,12,3],[8,2,7]])
print(arr11)
print(arr11.sum())
print(np.max(arr11 , axis=0))
print(np.min(arr11 , axis=0))

[[ 5 12  3]
 [ 8  2  7]]
37
[ 8 12  7]
[5 2 3]

In [152]:
print(arr1.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]]

## 3 Pandas DataFrame Detective

In [153]:
# Perform basic exploratory data analysis using Pandas.

import pandas as pd

data = {
'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
'Age': [25,30,np.nan,35,28,np.nan],
'Score': [85,92,78,np.nan,88,95],
'Grade': ['A','A','B','C','B','A']
}

df = pd.DataFrame(data)
df

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Frank   NaN   95.0     A

In [154]:
df.head(3)

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B

In [155]:
df.shape

(6, 4)

In [156]:
df.columns

Index(['Name', 'Age', 'Score', 'Grade'], dtype='str')

In [157]:
df.dtypes

Name         str
Age      float64
Score    float64
Grade        str
dtype: object

In [158]:
df.isnull().sum()

Name     0
Age      2
Score    1
Grade    0
dtype: int64

In [159]:
mean_age = df['Age'].mean()
print("Mean age:", mean_age)

Mean age: 29.5

In [160]:
df["Age"] = df["Age"].fillna(mean_age)
df

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Frank  29.5   95.0     A

In [161]:
df.dropna(inplace=True)
df

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
4      Eve  28.0   88.0     B
5    Frank  29.5   95.0     A

In [162]:
print(df[["Name", "Age"]])

      Name   Age
0    Alice  25.0
1      Bob  30.0
2  Charlie  29.5
4      Eve  28.0
5    Frank  29.5

In [163]:
high_scores = df[df['Score'] > 85]
print(high_scores)

    Name   Age  Score Grade
1    Bob  30.0   92.0     A
4    Eve  28.0   88.0     B
5  Frank  29.5   95.0     A

In [164]:
df.set_index('Name' , inplace=True)

In [165]:
df

          Age  Score Grade
Name
Alice    25.0   85.0     A
Bob      30.0   92.0     A
Charlie  29.5   78.0     B
Eve      28.0   88.0     B
Frank    29.5   95.0     A

In [166]:
unique_grades = df["Grade"].unique()
print(unique_grades)

<StringArray>
['A', 'B']
Length: 2, dtype: str

In [169]:
grade_counts = df['Grade'].value_counts()
print(grade_counts)

Grade
A    3
B    2
Name: count, dtype: int64

In [170]:
sorted_df = df.sort_values('Score', ascending=False)
print(sorted_df)

          Age  Score Grade
Name
Frank    29.5   95.0     A
Bob      30.0   92.0     A
Eve      28.0   88.0     B
Alice    25.0   85.0     A
Charlie  29.5   78.0     B